# Conclusion

After exploring the voting results and candidates' raisings and spendings, we have gained a more thorough understanding of the U.S. Presidential Election and obtained many interesting findings to answer questions we proposed in the beginning.

Under the background of COVID-19 pandemic, 2020 US Presidential Election was full of uncertainty. Joe Biden, the president-elect of the United States, flipped five states that Hilary Clinton lost in 2016 and achieved victories both in electoral votes and popular votes. By analyzing the shifts in popular vote shares from 2016 to 2020, we found that among US states, more than 40 states have shifted toward Democratics, which might reflect people's dissatisfaction with current government policies and response to COVID-19 this year. However, it seems that people's expectations on the leader are very dichotomized. Trump still won 25 states in this election and his popular margins in some states were as large as 40%, which means Trump's advocates did not waver on their position, and their solid support has been reflected by the significant individual contributions to Trump.

By analyzing the raisings and spendings of presidential election committees, we discovered that Joe Biden raised and spent much more than Donald Trump did during this year, which might be a sign of leading the election. When relating to the election results, parties which people in "blue states" or "red states" made contributions to were largely consistent with the states' voting choices, whereas it is hard to predict voting results by contributions in swing states. In spite of uncertain correlations, we did detect some differences between Biden's and Trump's contributors which may be useful in predicting voting outcomes. Regarding disbursements, Biden and Trump had different spending strategies that Biden invested the majority of funds in advertising and little in campaign trips, while Trump spent larger amounts in holding rallies and preparing campaign materials. By looking at the flipped states and the states each candidate has put the most efforts in, we found that Trump's strategy was not as effective in winning more votes in key states. 

Despite these findings, our analysis is limited. As we focused on data exploration, a lot of modelings can be applied to further examine the correlations between raisings, spendings, and voting results, which would lead to more meaningful insights. Also, we are not experts of US election laws and history that we were not able to dig deeper into the historical elections and relate them to the 2020 election. It would be interesting to explore how supporters of Democrats and Republicans have changed and shifted over time. 

In addition to limitations in analysis, there also existed limitations in data. Since this election year is very special under the COVID-19 pandemic, the data we used might not be normal or representative to draw the conclusions above. Besides, since the vote counting and post-election processing are still ongoing in some states, the datasets we used are still getting updated during our analysis process. We tried our best to retrieve the latest data, but the datasets to this point are still subject to change. We performed the analysis based upon FEC's [Pre-General Reports](https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2020-reporting-dates/2020-monthly-filers/) of raisings and spendings which do not contain records after October 15, 2020, therefore this analysis might not be able to capture the full picture of the 2020 U.S. Presidential Election up to the election day. Another issue with the data is around the mail-in voting fraud claims which have threatened the reliability of our data sources. Although we have carefully chosen the most authorized election statistics providers and verified the results from multiple sources, we are concerned about possible noise that might reduce the validity of our analysis. In the future, if the full election results are finalized and published by authorities, we will do further cross examination and complete a more comprehensive analysis. 

